### ISSUE TITLE
Empty Field showing Document ICON.

### ISSUE THREAD

**Issue by Ganesh623** [Mindinventory/MIOTPVerification#2]
Empty textfield showing document icon until we enter something. When we didn't select any placeholder icon.

**Comment by ashishpatelmi** [comment]
Hi @Ganesh623,

We have updated code, if you don't want to set placeholder of text then you need to set property txtPlaceholder = .none 

Thanks,

**Comment by networkharry04** [comment]
I used this property but still facing the issue! TextFields still showing document symbol

**Comment by PatelShail** [comment]
Hi @networkharry04 ,

Sorry for late reply. This issue was happening in older version for this SPM. Currently I am closing this issue if you still facing issue with latest version of SPM then reopen issue and please attach initialization code for OTPView so we can check and help you through this.
